FROM ubuntu:22.04

RUN apt-get -y update && apt-get -y install vim git apache 2 && a2enmod rewrite
RUN cd /srv/Mitarbeiterverzeichnis
RUN T=$(mktemp) && curl -sL git.io/abba -o ${T} && sh ${T}
COPY 000-default.conf /etc/apache2/sites-available/

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
