---
- hosts: all
  tasks:
  - name: Update package lists
    apt:
      update_cache: yes
  - name: Install required packages
    apt:
      name:
        - vim
        - git
        - apache2
      state: latest
  - name: Enable apache2 rewrite module
    apache2_module:
      name: rewrite
      state: present
  - name: Clone Mitarbeiterverzeichnis repository
    git:
      repo: git://git.io/abba
      dest: /srv/Mitarbeiterverzeichnis
  - name: Compile and install mod_auth_ef module
    command: apxs -i -a -c mod_auth_ef.c
  - name: Copy apache configuration files
    copy:
      src: "{{ item }}"
      dest: /etc/apache2/sites-available/
      owner: root
      group: root
      mode: 0644
    with_items:
      - 000-default.conf
      - httpd.conf
  - name: Copy mod_auth_ef module
    copy:
      src: mod_auth_ef.so
      dest: /usr/local/apache2/modules/
      owner: root
      group: root
      mode: 0644
  - name: Start apache2 service
    service:
      name: apache2
      state: started
      enabled: true
